[2025-03-29T14:58:13.918+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:58:14.114+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-03-29T14:58:14.209+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-03-29T14:58:14.212+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:58:14.984+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2025-03-03 00:00:00+00:00
[2025-03-29T14:58:15.019+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1827) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:58:15.043+0000] {standard_task_runner.py:72} INFO - Started process 1856 to run task
[2025-03-29T14:58:15.016+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'third_task', 'scheduled__2025-03-03T00:00:00+00:00', '--job-id', '593', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpv4oy15cg']
[2025-03-29T14:58:15.059+0000] {standard_task_runner.py:105} INFO - Job 593: Subtask third_task
[2025-03-29T14:58:15.405+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.third_task scheduled__2025-03-03T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:58:15.831+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T00:00:00+00:00'
[2025-03-29T14:58:15.837+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:58:15.896+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:58:15.902+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello, i am task3 and will be running after task1!']
[2025-03-29T14:58:15.944+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:58:15.946+0000] {subprocess.py:106} INFO - hello, i am task3 and will be running after task1!
[2025-03-29T14:58:15.947+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:58:16.045+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:58:16.062+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=third_task, run_id=scheduled__2025-03-03T00:00:00+00:00, execution_date=20250303T000000, start_date=20250329T145814, end_date=20250329T145816
[2025-03-29T14:58:16.210+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:58:16.250+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
