[2025-06-08T19:13:48.712+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-08T19:13:48.739+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ml_pipeline_docker_operator_v01.faked_dataset_creation_task manual__2025-06-08T19:10:00.803157+00:00 [queued]>
[2025-06-08T19:13:48.754+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ml_pipeline_docker_operator_v01.faked_dataset_creation_task manual__2025-06-08T19:10:00.803157+00:00 [queued]>
[2025-06-08T19:13:48.755+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-06-08T19:13:48.777+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): faked_dataset_creation_task> on 2025-06-08 19:10:00.803157+00:00
[2025-06-08T19:13:48.790+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=23184) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-08T19:13:48.788+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ml_pipeline_docker_operator_v01', 'faked_dataset_creation_task', 'manual__2025-06-08T19:10:00.803157+00:00', '--job-id', '1409', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_with_docker_operator.py', '--cfg-path', '/tmp/tmplc9xf5g9']
[2025-06-08T19:13:48.791+0000] {standard_task_runner.py:72} INFO - Started process 23185 to run task
[2025-06-08T19:13:48.792+0000] {standard_task_runner.py:105} INFO - Job 1409: Subtask faked_dataset_creation_task
[2025-06-08T19:13:48.860+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ml_pipeline_docker_operator_v01.faked_dataset_creation_task manual__2025-06-08T19:10:00.803157+00:00 [running]> on host e9ff53ca7e24
[2025-06-08T19:13:48.963+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acilrestu12' AIRFLOW_CTX_DAG_ID='dag_ml_pipeline_docker_operator_v01' AIRFLOW_CTX_TASK_ID='faked_dataset_creation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T19:10:00.803157+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T19:10:00.803157+00:00'
[2025-06-08T19:13:48.965+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-08T19:13:48.990+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-08T19:13:48.993+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\necho "Hey the dataset is ready, let\'s trigger the training process"']
[2025-06-08T19:13:49.012+0000] {subprocess.py:99} INFO - Output:
[2025-06-08T19:13:49.015+0000] {subprocess.py:106} INFO - Hey the dataset is ready, let's trigger the training process
[2025-06-08T19:13:49.016+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-06-08T19:13:49.277+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-08T19:13:49.278+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_ml_pipeline_docker_operator_v01, task_id=faked_dataset_creation_task, run_id=manual__2025-06-08T19:10:00.803157+00:00, execution_date=20250608T191000, start_date=20250608T191348, end_date=20250608T191349
[2025-06-08T19:13:49.330+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-08T19:13:49.384+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-08T19:13:49.389+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
