[2025-03-29T14:55:51.265+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:55:51.388+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2024-12-18T00:00:00+00:00 [queued]>
[2025-03-29T14:55:51.485+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2024-12-18T00:00:00+00:00 [queued]>
[2025-03-29T14:55:51.500+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:55:51.629+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2024-12-18 00:00:00+00:00
[2025-03-29T14:55:51.676+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=245) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:55:51.680+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'third_task', 'scheduled__2024-12-18T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp8rg_zq3t']
[2025-03-29T14:55:51.723+0000] {standard_task_runner.py:72} INFO - Started process 263 to run task
[2025-03-29T14:55:51.740+0000] {standard_task_runner.py:105} INFO - Job 162: Subtask third_task
[2025-03-29T14:55:52.450+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.third_task scheduled__2024-12-18T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:55:53.904+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T00:00:00+00:00'
[2025-03-29T14:55:53.925+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:55:54.080+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:55:54.101+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello, i am task3 and will be running after task1!']
[2025-03-29T14:55:54.157+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:55:54.165+0000] {subprocess.py:106} INFO - hello, i am task3 and will be running after task1!
[2025-03-29T14:55:54.168+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:55:54.519+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:55:54.546+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=third_task, run_id=scheduled__2024-12-18T00:00:00+00:00, execution_date=20241218T000000, start_date=20250329T145551, end_date=20250329T145554
[2025-03-29T14:55:54.807+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:55:55.272+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T14:55:55.306+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
