[2025-03-29T14:56:37.889+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:56:37.961+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-01-10T00:00:00+00:00 [queued]>
[2025-03-29T14:56:38.048+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-01-10T00:00:00+00:00 [queued]>
[2025-03-29T14:56:38.064+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:56:38.287+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2025-01-10 00:00:00+00:00
[2025-03-29T14:56:38.343+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=706) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:56:38.346+0000] {standard_task_runner.py:72} INFO - Started process 725 to run task
[2025-03-29T14:56:38.366+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'third_task', 'scheduled__2025-01-10T00:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp9m4ml06z']
[2025-03-29T14:56:38.377+0000] {standard_task_runner.py:105} INFO - Job 282: Subtask third_task
[2025-03-29T14:56:38.781+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.third_task scheduled__2025-01-10T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:56:39.303+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-10T00:00:00+00:00'
[2025-03-29T14:56:39.306+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:56:39.416+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:56:39.434+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello, i am task3 and will be running after task1!']
[2025-03-29T14:56:39.484+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:56:39.499+0000] {subprocess.py:106} INFO - hello, i am task3 and will be running after task1!
[2025-03-29T14:56:39.504+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:56:39.613+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:56:39.615+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=third_task, run_id=scheduled__2025-01-10T00:00:00+00:00, execution_date=20250110T000000, start_date=20250329T145637, end_date=20250329T145639
[2025-03-29T14:56:39.759+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:56:39.805+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T14:56:39.818+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
