[2025-03-29T14:58:49.489+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:58:49.749+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-03-19T00:00:00+00:00 [queued]>
[2025-03-29T14:58:49.920+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-03-19T00:00:00+00:00 [queued]>
[2025-03-29T14:58:49.949+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:58:50.385+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2025-03-19 00:00:00+00:00
[2025-03-29T14:58:50.504+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'third_task', 'scheduled__2025-03-19T00:00:00+00:00', '--job-id', '693', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpy4dm2kgk']
[2025-03-29T14:58:50.513+0000] {standard_task_runner.py:105} INFO - Job 693: Subtask third_task
[2025-03-29T14:58:50.506+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2177) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:58:50.517+0000] {standard_task_runner.py:72} INFO - Started process 2216 to run task
[2025-03-29T14:58:50.957+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.third_task scheduled__2025-03-19T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:58:51.651+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-19T00:00:00+00:00'
[2025-03-29T14:58:51.668+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:58:51.760+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:58:51.773+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello, i am task3 and will be running after task1!']
[2025-03-29T14:58:51.814+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:58:51.818+0000] {subprocess.py:106} INFO - hello, i am task3 and will be running after task1!
[2025-03-29T14:58:51.847+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:58:52.098+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:58:52.111+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=third_task, run_id=scheduled__2025-03-19T00:00:00+00:00, execution_date=20250319T000000, start_date=20250329T145849, end_date=20250329T145852
[2025-03-29T14:58:52.285+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:58:52.322+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
