[2025-03-29T14:58:01.382+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:58:01.459+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-02-24T00:00:00+00:00 [queued]>
[2025-03-29T14:58:01.490+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-02-24T00:00:00+00:00 [queued]>
[2025-03-29T14:58:01.492+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:58:01.534+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2025-02-24 00:00:00+00:00
[2025-03-29T14:58:01.574+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1671) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:58:01.581+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'third_task', 'scheduled__2025-02-24T00:00:00+00:00', '--job-id', '545', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpv2yjsmrn']
[2025-03-29T14:58:01.599+0000] {standard_task_runner.py:105} INFO - Job 545: Subtask third_task
[2025-03-29T14:58:01.596+0000] {standard_task_runner.py:72} INFO - Started process 1689 to run task
[2025-03-29T14:58:01.732+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.third_task scheduled__2025-02-24T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:58:01.949+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-24T00:00:00+00:00'
[2025-03-29T14:58:01.950+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:58:01.975+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:58:01.977+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello, i am task3 and will be running after task1!']
[2025-03-29T14:58:01.994+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:58:01.997+0000] {subprocess.py:106} INFO - hello, i am task3 and will be running after task1!
[2025-03-29T14:58:01.998+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:58:02.042+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:58:02.044+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=third_task, run_id=scheduled__2025-02-24T00:00:00+00:00, execution_date=20250224T000000, start_date=20250329T145801, end_date=20250329T145802
[2025-03-29T14:58:02.116+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:58:02.147+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T14:58:02.155+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
