[2025-04-02T20:29:47.996+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-02T20:29:48.110+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_cron_expression_v03.task1 scheduled__2025-03-18T03:10:00+00:00 [queued]>
[2025-04-02T20:29:48.158+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_cron_expression_v03.task1 scheduled__2025-03-18T03:10:00+00:00 [queued]>
[2025-04-02T20:29:48.165+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-04-02T20:29:48.367+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task1> on 2025-03-18 03:10:00+00:00
[2025-04-02T20:29:48.417+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_cron_expression_v03', 'task1', 'scheduled__2025-03-18T03:10:00+00:00', '--job-id', '832', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_cron_expression.py', '--cfg-path', '/tmp/tmp8qjyra5m']
[2025-04-02T20:29:48.423+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=661) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-02T20:29:48.424+0000] {standard_task_runner.py:105} INFO - Job 832: Subtask task1
[2025-04-02T20:29:48.425+0000] {standard_task_runner.py:72} INFO - Started process 674 to run task
[2025-04-02T20:29:48.583+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_cron_expression_v03.task1 scheduled__2025-03-18T03:10:00+00:00 [running]> on host ba06481f48a9
[2025-04-02T20:29:48.884+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acilrestu12' AIRFLOW_CTX_DAG_ID='dag_with_cron_expression_v03' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T03:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-18T03:10:00+00:00'
[2025-04-02T20:29:48.887+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-02T20:29:48.967+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-02T20:29:48.976+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "DAG with cron expression executed"']
[2025-04-02T20:29:49.021+0000] {subprocess.py:99} INFO - Output:
[2025-04-02T20:29:49.043+0000] {subprocess.py:106} INFO - DAG with cron expression executed
[2025-04-02T20:29:49.052+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-02T20:29:49.152+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-02T20:29:49.160+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_cron_expression_v03, task_id=task1, run_id=scheduled__2025-03-18T03:10:00+00:00, execution_date=20250318T031000, start_date=20250402T202948, end_date=20250402T202949
[2025-04-02T20:29:49.285+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-02T20:29:49.398+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T20:29:49.427+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
