[2025-03-29T14:56:14.115+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:56:14.282+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2025-03-29T14:56:14.381+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2025-03-29T14:56:14.408+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:56:14.771+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2024-12-28 00:00:00+00:00
[2025-03-29T14:56:14.882+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=448) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:56:14.886+0000] {standard_task_runner.py:72} INFO - Started process 482 to run task
[2025-03-29T14:56:14.864+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'third_task', 'scheduled__2024-12-28T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpxbwjxwjv']
[2025-03-29T14:56:14.900+0000] {standard_task_runner.py:105} INFO - Job 215: Subtask third_task
[2025-03-29T14:56:15.483+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.third_task scheduled__2024-12-28T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:56:16.676+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T00:00:00+00:00'
[2025-03-29T14:56:16.679+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:56:16.826+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:56:16.860+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello, i am task3 and will be running after task1!']
[2025-03-29T14:56:17.157+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:56:17.183+0000] {subprocess.py:106} INFO - hello, i am task3 and will be running after task1!
[2025-03-29T14:56:17.195+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:56:17.540+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:56:17.541+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=third_task, run_id=scheduled__2024-12-28T00:00:00+00:00, execution_date=20241228T000000, start_date=20250329T145614, end_date=20250329T145617
[2025-03-29T14:56:17.912+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:56:18.081+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T14:56:18.138+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
