[2025-04-04T23:16:30.695+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-04T23:16:30.725+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T23:16:30.741+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T23:16:30.742+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 8
[2025-04-04T23:16:30.767+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2025-04-03 00:00:00+00:00
[2025-04-04T23:16:30.783+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1487) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-04T23:16:30.782+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '861', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpyzneqj_5']
[2025-04-04T23:16:30.785+0000] {standard_task_runner.py:72} INFO - Started process 1488 to run task
[2025-04-04T23:16:30.785+0000] {standard_task_runner.py:105} INFO - Job 861: Subtask insert_into_table
[2025-04-04T23:16:30.866+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-04-03T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-04-04T23:16:30.986+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acilrestu12' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-04T23:16:30.988+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-04T23:16:31.012+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO dag_runs (dt, dag_id, run_id)
            VALUES ('2025-04-03', 'dag_with_postgres_operator_v03', 'scheduled__2025-04-03T00:00:00+00:00');
        
[2025-04-04T23:16:31.025+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-04-04T23:16:31.038+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-04-04T23:16:31.056+0000] {sql.py:544} INFO - Running statement: 
            INSERT INTO dag_runs (dt, dag_id, run_id)
            VALUES ('2025-04-03', 'dag_with_postgres_operator_v03', 'scheduled__2025-04-03T00:00:00+00:00');
        , parameters: None
[2025-04-04T23:16:31.063+0000] {sql.py:553} INFO - Rows affected: 1
[2025-04-04T23:16:31.083+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-04T23:16:31.084+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250404T231630, end_date=20250404T231631
[2025-04-04T23:16:31.122+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-04T23:16:31.146+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T23:16:31.150+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
