[2025-04-08T11:44:43.153+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T11:44:43.220+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v03.postgres_to_s3 scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-08T11:44:43.243+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v03.postgres_to_s3 scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-08T11:44:43.247+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-04-08T11:44:43.293+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2025-04-07 00:00:00+00:00
[2025-04-08T11:44:43.332+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15120) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T11:44:43.320+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v03', 'postgres_to_s3', 'scheduled__2025-04-07T00:00:00+00:00', '--job-id', '1024', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpenyq6cmw']
[2025-04-08T11:44:43.334+0000] {standard_task_runner.py:72} INFO - Started process 15127 to run task
[2025-04-08T11:44:43.335+0000] {standard_task_runner.py:105} INFO - Job 1024: Subtask postgres_to_s3
[2025-04-08T11:44:43.488+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_hooks_v03.postgres_to_s3 scheduled__2025-04-07T00:00:00+00:00 [running]> on host e9ff53ca7e24
[2025-04-08T11:44:43.748+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acilrestu12' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v03' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-07T00:00:00+00:00'
[2025-04-08T11:44:43.750+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-08T11:44:43.806+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py:175 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2025-04-08T11:44:43.828+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-04-08T11:44:43.891+0000] {dag_with_postgres_hooks.py:29} INFO - Saved orders data in the file get_orders.txt
[2025-04-08T11:44:43.897+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T11:44:43.933+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-08T11:44:43.935+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v03, task_id=postgres_to_s3, run_id=scheduled__2025-04-07T00:00:00+00:00, execution_date=20250407T000000, start_date=20250408T114443, end_date=20250408T114443
[2025-04-08T11:44:43.998+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T11:44:44.039+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T11:44:44.044+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
