[2025-03-29T14:55:50.925+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:55:51.275+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.second_task scheduled__2024-12-20T00:00:00+00:00 [queued]>
[2025-03-29T14:55:51.354+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.second_task scheduled__2024-12-20T00:00:00+00:00 [queued]>
[2025-03-29T14:55:51.369+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:55:51.479+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2024-12-20 00:00:00+00:00
[2025-03-29T14:55:51.517+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:55:51.523+0000] {standard_task_runner.py:72} INFO - Started process 261 to run task
[2025-03-29T14:55:51.516+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'second_task', 'scheduled__2024-12-20T00:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpx5bby_2b']
[2025-03-29T14:55:51.559+0000] {standard_task_runner.py:105} INFO - Job 157: Subtask second_task
[2025-03-29T14:55:52.005+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.second_task scheduled__2024-12-20T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:55:52.947+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-20T00:00:00+00:00'
[2025-03-29T14:55:52.963+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:55:53.144+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:55:53.166+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, i am task2 and will be running after task1!']
[2025-03-29T14:55:53.226+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:55:53.239+0000] {subprocess.py:106} INFO - hey, i am task2 and will be running after task1!
[2025-03-29T14:55:53.241+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:55:53.598+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:55:53.706+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=second_task, run_id=scheduled__2024-12-20T00:00:00+00:00, execution_date=20241220T000000, start_date=20250329T145551, end_date=20250329T145553
[2025-03-29T14:55:54.083+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:55:54.139+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
