[2025-03-29T14:56:54.962+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:56:55.098+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-03-29T14:56:55.187+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-03-29T14:56:55.200+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:56:55.603+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2025-01-21 00:00:00+00:00
[2025-03-29T14:56:55.632+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'third_task', 'scheduled__2025-01-21T00:00:00+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpf24_1il6']
[2025-03-29T14:56:55.639+0000] {standard_task_runner.py:105} INFO - Job 341: Subtask third_task
[2025-03-29T14:56:55.647+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=898) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:56:55.670+0000] {standard_task_runner.py:72} INFO - Started process 933 to run task
[2025-03-29T14:56:56.068+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.third_task scheduled__2025-01-21T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:56:56.563+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T00:00:00+00:00'
[2025-03-29T14:56:56.566+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:56:56.704+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:56:56.707+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello, i am task3 and will be running after task1!']
[2025-03-29T14:56:56.771+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:56:56.774+0000] {subprocess.py:106} INFO - hello, i am task3 and will be running after task1!
[2025-03-29T14:56:56.775+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:56:56.893+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:56:56.896+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=third_task, run_id=scheduled__2025-01-21T00:00:00+00:00, execution_date=20250121T000000, start_date=20250329T145655, end_date=20250329T145656
[2025-03-29T14:56:57.050+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:56:57.135+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T14:56:57.162+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
