[2025-04-02T20:06:27.583+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-02T20:06:27.627+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 backfill__2025-03-26T00:00:00+00:00 [queued]>
[2025-04-02T20:06:27.649+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 backfill__2025-03-26T00:00:00+00:00 [queued]>
[2025-04-02T20:06:27.651+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-04-02T20:06:27.722+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task1> on 2025-03-26 00:00:00+00:00
[2025-04-02T20:06:27.754+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=956) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-02T20:06:27.758+0000] {standard_task_runner.py:72} INFO - Started process 973 to run task
[2025-04-02T20:06:27.755+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v02', 'task1', 'backfill__2025-03-26T00:00:00+00:00', '--job-id', '800', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpijs13xqy']
[2025-04-02T20:06:27.767+0000] {standard_task_runner.py:105} INFO - Job 800: Subtask task1
[2025-04-02T20:06:27.947+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backfill_v02.task1 backfill__2025-03-26T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-04-02T20:06:28.254+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acilrestu12' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backfill_v02' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2025-03-26T00:00:00+00:00'
[2025-04-02T20:06:28.259+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-02T20:06:28.265+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-02T20:06:28.268+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Task 1 executed"']
[2025-04-02T20:06:28.301+0000] {subprocess.py:99} INFO - Output:
[2025-04-02T20:06:28.304+0000] {subprocess.py:106} INFO - Task 1 executed
[2025-04-02T20:06:28.305+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-02T20:06:28.385+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-02T20:06:28.386+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backfill_v02, task_id=task1, run_id=backfill__2025-03-26T00:00:00+00:00, execution_date=20250326T000000, start_date=20250402T200627, end_date=20250402T200628
[2025-04-02T20:06:28.485+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-02T20:06:28.515+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T20:06:28.522+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
