[2025-03-29T14:57:02.381+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:57:02.474+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.second_task scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-03-29T14:57:02.529+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.second_task scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-03-29T14:57:02.532+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:57:02.688+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2025-01-24 00:00:00+00:00
[2025-03-29T14:57:02.738+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=977) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:57:02.753+0000] {standard_task_runner.py:72} INFO - Started process 988 to run task
[2025-03-29T14:57:02.753+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'second_task', 'scheduled__2025-01-24T00:00:00+00:00', '--job-id', '354', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpmko9trlq']
[2025-03-29T14:57:02.760+0000] {standard_task_runner.py:105} INFO - Job 354: Subtask second_task
[2025-03-29T14:57:03.102+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.second_task scheduled__2025-01-24T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:57:03.721+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-24T00:00:00+00:00'
[2025-03-29T14:57:03.737+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:57:03.936+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:57:03.968+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, i am task2 and will be running after task1!']
[2025-03-29T14:57:04.097+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:57:04.164+0000] {subprocess.py:106} INFO - hey, i am task2 and will be running after task1!
[2025-03-29T14:57:04.239+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:57:04.561+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:57:04.588+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=second_task, run_id=scheduled__2025-01-24T00:00:00+00:00, execution_date=20250124T000000, start_date=20250329T145702, end_date=20250329T145704
[2025-03-29T14:57:04.846+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:57:04.964+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T14:57:05.032+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
